# Generated by Django 2.1.1 on 2021-05-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210510_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='address',
        ),
        migrations.AddField(
            model_name='addresses',
            name='address_1',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='addresses',
            name='address_2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addresses',
            name='city_or_district',
            field=models.CharField(default='NA', max_length=128),
        ),
        migrations.AddField(
            model_name='addresses',
            name='contact_name',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='addresses',
            name='contact_number',
            field=models.CharField(default='NA', max_length=15),
        ),
        migrations.AddField(
            model_name='addresses',
            name='country',
            field=models.CharField(default='NA', max_length=128),
        ),
        migrations.AddField(
            model_name='addresses',
            name='delivery_instructions',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addresses',
            name='is_primary_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addresses',
            name='nearby_location',
            field=models.CharField(default='NA', max_length=128),
        ),
        migrations.AddField(
            model_name='addresses',
            name='pincode',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='addresses',
            name='state',
            field=models.CharField(default='NA', max_length=128),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='address_type',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
