# Generated by Django 2.1.1 on 2021-06-06 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_auto_20210606_1334'),
        ('accounts', '0003_auto_20210510_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_name', models.SlugField(blank=True, default='slug', max_length=255, null=True, unique=True)),
                ('added_on', models.DateField(auto_now=True)),
                ('misc_attr_1', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField(auto_now=True)),
                ('misc_attr_1', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('product_sku_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products', to_field='product_sku_number')),
                ('user_wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_owner', to='accounts.WishList')),
            ],
        ),
    ]
