# Generated by Django 2.1.1 on 2021-05-18 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku_number', models.CharField(default=1, max_length=64)),
                ('product_img_url', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('date_uploaded', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('parent_sku_number', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('product_sku_number', models.CharField(max_length=64, unique=True)),
                ('product_category', models.CharField(max_length=255)),
                ('product_brand', models.CharField(max_length=255)),
                ('product_manufracturer', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_units', models.IntegerField(default=1)),
                ('package_units', models.IntegerField(default=1)),
                ('date_first_available', models.DateField(auto_now=True)),
                ('asin_number', models.CharField(max_length=255)),
                ('item_model_number', models.CharField(max_length=255)),
                ('country_of_origin', models.CharField(max_length=64)),
                ('packer', models.CharField(max_length=255)),
                ('importer', models.CharField(max_length=255)),
                ('included_components', models.CharField(max_length=512)),
                ('product_height', models.CharField(blank=True, max_length=20, null=True)),
                ('product_width', models.CharField(blank=True, max_length=20, null=True)),
                ('product_length', models.CharField(blank=True, max_length=20, null=True)),
                ('product_weight', models.CharField(blank=True, max_length=20, null=True)),
                ('product_height_dim', models.CharField(blank=True, max_length=20, null=True)),
                ('product_width_dim', models.CharField(blank=True, max_length=20, null=True)),
                ('product_length_dim', models.CharField(blank=True, max_length=20, null=True)),
                ('product_weight_dim', models.CharField(blank=True, max_length=20, null=True)),
                ('product_description', models.CharField(blank=True, max_length=512, null=True)),
                ('product_active', models.BooleanField(default=True)),
                ('product_expired', models.DateField(blank=True, default=None, null=True)),
                ('product_expired_by', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('legal_disclaimer', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('color_available', models.CharField(max_length=128)),
                ('featured_content', models.BooleanField(default=False)),
                ('size_variants', models.CharField(blank=True, default='', max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku_number', models.CharField(default=1, max_length=64)),
                ('product_specs_title', models.CharField(default='x', max_length=64)),
                ('product_specs', models.CharField(max_length=255)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='uploaded_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
