# Generated by Django 2.1.1 on 2021-05-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='misc_attr_1',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
