# Generated by Django 2.1.1 on 2021-05-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_misc_attr_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='misc_attr_1',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='misc_attr_1',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
