# Generated by Django 2.1.1 on 2021-05-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210518_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='date_uploaded',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='date_first_available',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='created_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='updated_on',
            field=models.DateField(),
        ),
    ]
