# Generated by Django 2.1.1 on 2021-05-18 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210518_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='product',
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product_sku_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products', to_field='product_sku_number'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product_sku_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products', to_field='product_sku_number'),
        ),
    ]
