# Generated by Django 2.1.1 on 2021-06-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210518_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
