# Generated by Django 2.1.1 on 2021-06-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
