# Generated by Django 2.1.1 on 2021-06-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210606_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True),
        ),
    ]
